Update todos, add tests to workflow

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -40,3 +40,7 @@ jobs:
       - name: Run clippy
         if: success() || failure()  # Run even if fmt fails
         run: cargo clippy -- -D warnings
+
+      - name: Run tests
+        if: success() || failure()  # Run even if previous steps fail
+        run: cargo test --verbose
