Release mvp version of e2e miner, validator, orchestrator and discovery service
Ship initial e2e working version

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -5,14 +5,12 @@ on:
     branches: [ main, master, develop ]
     paths:
       - '**.rs'
-      - 'miner/**'
-      - 'Cargo.*'
+      - '**/Cargo.*'
   push:
     branches: [ main, master, develop ]
     paths:
       - '**.rs'
-      - 'miner/**'
-      - 'Cargo.*'
+      - '**/Cargo.*'
 
 env:
   CARGO_TERM_COLOR: always
@@ -28,19 +26,21 @@ jobs:
 
       - uses: dtolnay/rust-toolchain@master
         with:
-          toolchain: stable
+          toolchain: 1.83.0 
           components: rustfmt, clippy
 
       - uses: Swatinem/rust-cache@v2
         with:
-          cache-directories: "miner/target"
+          cache-directories: "**/target"
           cache-on-failure: true
           
       - name: Run format check
-        working-directory: ./miner
         run: cargo fmt -- --check
 
       - name: Run clippy
         if: success() || failure()  # Run even if fmt fails
-        working-directory: ./miner
         run: cargo clippy -- -D warnings
+
+      # - name: Run tests
+      #   if: success() || failure()  # Run even if previous steps fail
+      #   run: cargo test --verbose
