attempt to fix tests in toolchain

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -41,6 +41,9 @@ jobs:
         if: success() || failure()  # Run even if fmt fails
         run: cargo clippy -- -D warnings
 
-      # - name: Run tests
-      #   if: success() || failure()  # Run even if previous steps fail
-      #   run: cargo test --verbose
+       - name: Install Redis
+         run: sudo apt-get update && sudo apt-get install -y redis-server
+
+       - name: Run tests
+         if: success() || failure()  # Run even if previous steps fail
+         run: cargo test --verbose
