disable tests

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -36,16 +36,16 @@ jobs:
       - name: Run clippy
         if: success() || failure() 
         run: cargo clippy -- -D warnings
-      - name: Install Redis binary
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y redis-server
-          # Ensure redis-server binary is installed but don't start the service
-          sudo systemctl stop redis || true
-          sudo systemctl disable redis || true
+      #- name: Install Redis binary
+        #run: |
+          #sudo apt-get update
+          #sudo apt-get install -y redis-server
+          ## Ensure redis-server binary is installed but don't start the service
+          #sudo systemctl stop redis || true
+          #sudo systemctl disable redis || true
           
-      - name: Run tests
-        if: success() || failure()  
-        run: |
-          redis-server --version
-          cargo test -- --nocapture
+      #- name: Run tests
+        #if: success() || failure()  
+        #run: |
+          #redis-server --version
+          #cargo test -- --nocapture
